

AUTH_ERROR = "AUTH_ERROR"
NO_TASK = "NO_TASK"
NO_RESPONSE = "NO_RESPONSE"
BAD_PASSWORD = "BAD_PASSWORD"
NOT_RUNNING = "NOT_RUNNING"
ALREADY_RUNNING = "ALREADY_RUNNING"
RESOURCE_BUSY = "RESOURCE_BUSY"
FILE_NOT_EXIST = "FILE_NOT_EXIST"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
UNKNOW_COMMAND = "UNKNOW_COMMAND"
UNKNOW_ERROR = "UNKNOW_ERROR"
