
# Permission related
AUTH_ERROR = "AUTH_ERROR"
BAD_PASSWORD = "BAD_PASSWORD"

# Communicate related
PROTOCOL_ERROR = "PROTOCOL_ERROR"
UNKNOW_COMMAND = "UNKNOW_COMMAND"
UNKNOW_ERROR = "UNKNOW_ERROR"

# Operation related
ALREADY_RUNNING = "ALREADY_RUNNING"
NOT_RUNNING = "NOT_RUNNING"
NOT_SUPPORT = "NOT_SUPPORT"
NO_TASK = "NO_TASK"
NO_RESPONSE = "NO_RESPONSE"
DEVICE_ERROR = "DEVICE_ERROR"
RESOURCE_BUSY = "RESOURCE_BUSY"

# Date related
NOT_EXIST = "NOT_EXIST"
TOO_LARGE = "TOO_LARGE"
NOT_MATCH = "NOT_MATCH"
