

BAD_PASSWORD = "BAD_PASSWORD"
NOT_RUNNING = "NOT_RUNNING"
ALREADY_RUNNING = "ALREADY_RUNNING"
FILE_NOT_EXIST = "FILE_NOT_EXIST"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
UNKNOW_COMMAND = "UNKNOW_COMMAND"
UNKNOW_ERROR = "UNKNOW_ERROR"
