/* Generated by Cython 0.25.1 */

#ifndef __PYX_HAVE__fluxmonitor__security___security
#define __PYX_HAVE__fluxmonitor__security___security


#ifndef __PYX_HAVE_API__fluxmonitor__security___security

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *platform;
__PYX_EXTERN_C DL_IMPORT(PyObject) *is_dev_model;

#endif /* !__PYX_HAVE_API__fluxmonitor__security___security */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_security(void);
#else
PyMODINIT_FUNC PyInit__security(void);
#endif

#endif /* !__PYX_HAVE__fluxmonitor__security___security */
